name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Cache docs theme
        uses: actions/cache@v4
        with:
          path: docs/.theme
          key: ${{ runner.os }}-docs-theme-${{ hashFiles('docs/theme.toml') }}

      - name: Install MkDocs
        run: python3 -m pip install --upgrade pip mkdocs-material mkdocs-static-i18n

      - name: Fetch Docs Theme
        run: ./scripts/fetch-theme.sh
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Build
        run: mkdocs build --strict
